name = "OHDSICohortExpressions"
uuid = "b1469e29-13af-4897-a4a9-3c363a260582"
authors = ["Kirill Simonov <xi@resolvent.net>",
           "Clark C. Evans <cce@clarkevans.com>"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
FunSQL = "cf6cc811-59f4-4a10-b258-a8547a8f6407"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
PrettyPrinting = "54e16d92-306c-5ea0-a30b-337be88ac337"

[compat]
julia = "1.4"
FunSQL = "0.6.0"
PrettyPrinting = "0.3.2"
JSON = "0.21"
