name: CI
on:
  push:
    branches: [main]
    tags: ['*']
  pull_request:
  schedule:
  - cron: '0 0 1 * *'
jobs:
  test:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - name: Julia LTS / Linux 64bit
          version: '1.6'
          os: ubuntu-latest
          arch: x64
        - name: Julia LTS / Linux 32bit
          version: '1.6'
          os: ubuntu-latest
          arch: x86
        - name: Julia Stable / Linux 64bit
          version: '1'
          os: ubuntu-latest
          arch: x64
        - name: Julia Stable / Linux 32bit
          version: '1'
          os: ubuntu-latest
          arch: x86
        - name: Julia Stable / MacOS 64bit
          version: '1'
          os: macos-latest
          arch: x64
        - name: Julia Stable / Windows 64bit
          version: '1'
          os: windows-latest
          arch: x64
        - name: Julia Stable / Windows 32bit
          version: '1'
          os: windows-latest
          arch: x86
        - name: Julia Nightly / Linux 64bit
          version: nightly
          os: ubuntu-latest
          arch: x64
        - name: Julia Nightly / Linux 32bit
          version: nightly
          os: ubuntu-latest
          arch: x86
    steps:
    - uses: actions/checkout@v4
    - uses: julia-actions/setup-julia@v1
      with:
        version: ${{ matrix.version }}
        arch: ${{ matrix.arch }}
    - uses: julia-actions/cache@v1
    - uses: julia-actions/julia-buildpkg@v1
